name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8, 3.9, 3.10, 3.11]
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install build dependencies
        run: pip install --upgrade pip setuptools wheel build
      
      - name: Install test dependencies
        run: |
          pip install -e .[test]

      - name: Test with pytest
        run: pytest --maxfail=1 --disable-warnings -q

      - name: Build dist
        run: python -m build

      - name: Upload dist artifacts
        uses: actions/upload-artifact@v3
        with:
          name: dist-${{ matrix.python-version }}
          path: dist
