name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        python-version: ["3.9", "3.10", "3.11", "3.12"]

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pip'
          cache-dependency-path: |
            requirements.txt
            setup.py
            .github/workflows/ci.yml

      - name: Install build dependencies
        run: pip install --upgrade pip setuptools wheel build

      - name: Install test and lint dependencies
        run: |
          pip install -e .[test] pytest pylint

      - name: Run tests with pytest
        run: pytest --maxfail=1 --disable-warnings -q

      - name: Run linting with pylint
        run: pylint src --ignore=tests --disable=missing-module-docstring,missing-class-docstring,missing-function-docstring,invalid-name,too-few-public-methods,too-many-arguments,too-many-instance-attributes,too-many-locals,too-many-statements,too-many-branches,too-many-return-statements --fail-under 8
        env:
          PYTHONPATH: src

      - name: Build dist
        run: python -m build

      - name: Upload dist artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dist-${{ matrix.os }}-py${{ matrix.python-version }}
          path: dist